version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    networks:
      - homelab_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ:-Asia/Shanghai}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 2 * * *
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_TIMEOUT=30s
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=telegram://${TELEGRAM_TOKEN}@telegram/?channels=${TELEGRAM_CHAT_ID}
      - WATCHTOWER_NOTIFICATION_TITLE_TAG=Mac mini Home Lab
      - WATCHTOWER_POLL_INTERVAL=24h
      - WATCHTOWER_LABEL_ENABLE=true
    labels:
      - "com.github.dockge.name=watchtower"
      - "com.github.dockge.description=Docker容器自动更新服务"
      - "com.github.dockge.icon=https://raw.githubusercontent.com/containrrr/watchtower/main/logo.png"

networks:
  homelab_network:
    external: true
    name: ${NETWORK_NAME:-homelab_network}
