version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      - homelab_network
    volumes:
      - ${DATA_PATH:-./data}/monitoring/prometheus/config:/etc/prometheus
      - ${DATA_PATH:-./data}/monitoring/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    environment:
      - TZ=${TZ:-Asia/Shanghai}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.github.dockge.name=prometheus"
      - "com.github.dockge.description=时序数据监控系统"
      - "com.github.dockge.icon=https://prometheus.io/assets/favicons/favicon.ico"
      - "com.github.dockge.web=http://prometheus.${DOMAINNAME:-home.local}"
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAINNAME:-home.local}`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls=true"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - homelab_network
    depends_on:
      - prometheus
    volumes:
      - ${DATA_PATH:-./data}/monitoring/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-change_me_now}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=grafana.${DOMAINNAME:-home.local}
      - TZ=${TZ:-Asia/Shanghai}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.github.dockge.name=grafana"
      - "com.github.dockge.description=数据可视化与监控平台"
      - "com.github.dockge.icon=https://grafana.com/static/assets/img/fav32.png"
      - "com.github.dockge.web=http://grafana.${DOMAINNAME:-home.local}"
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAINNAME:-home.local}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    networks:
      - homelab_network
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2)($|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - 9100:9100
    environment:
      - TZ=${TZ:-Asia/Shanghai}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9100/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.github.dockge.name=node-exporter"
      - "com.github.dockge.description=系统指标导出器"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    networks:
      - homelab_network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8080:8080
    environment:
      - TZ=${TZ:-Asia/Shanghai}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.github.dockge.name=cadvisor"
      - "com.github.dockge.description=容器资源监控"

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    networks:
      - homelab_network
    volumes:
      - ${DATA_PATH:-./data}/uptime-kuma:/app/data
    ports:
      - 3001:3001
    environment:
      - TZ=${TZ:-Asia/Shanghai}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.github.dockge.name=uptime-kuma"
      - "com.github.dockge.description=服务监控与可用性检测"
      - "com.github.dockge.icon=https://uptime.kuma.pet/img/icon.svg"
      - "com.github.dockge.web=http://uptime.${DOMAINNAME:-home.local}"
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.rule=Host(`uptime.${DOMAINNAME:-home.local}`)"
      - "traefik.http.routers.uptime.entrypoints=websecure"
      - "traefik.http.routers.uptime.tls=true"

networks:
  homelab_network:
    external: true
    name: ${NETWORK_NAME:-homelab_network}
