version: '3.8'

services:
  nextcloud-db:
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: unless-stopped
    networks:
      - homelab_network
    volumes:
      - ${DATA_PATH:-./data}/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-change_me_now}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD:-change_me_now}
      - TZ=${TZ:-Asia/Shanghai}
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - homelab_network
    volumes:
      - ${DATA_PATH:-./data}/nextcloud/redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-change_me_now}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-change_me_now}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - homelab_network
    volumes:
      - ${DATA_PATH:-./data}/nextcloud/html:/var/www/html
      - ${MEDIA_PATH:-./media}:/media:ro
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD:-change_me_now}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-admin}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-change_me_now}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS:-nextcloud.home.local}
      - REDIS_HOST=nextcloud-redis
      - REDIS_PASSWORD=${REDIS_PASSWORD:-change_me_now}
      - PHP_MEMORY_LIMIT=1G
      - UPLOAD_MAX_SIZE=10G
      - TZ=${TZ:-Asia/Shanghai}
    ports:
      - 8080:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.github.dockge.name=nextcloud"
      - "com.github.dockge.description=私有云存储平台"
      - "com.github.dockge.icon=https://nextcloud.com/wp-content/uploads/2022/03/favicon.png"
      - "com.github.dockge.web=http://nextcloud.${DOMAINNAME:-home.local}"
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAINNAME:-home.local}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"

  nextcloud-cron:
    image: nextcloud:latest
    container_name: nextcloud-cron
    restart: unless-stopped
    volumes:
      - ${DATA_PATH:-./data}/nextcloud/html:/var/www/html
    networks:
      - homelab_network
    depends_on:
      - nextcloud-db
      - nextcloud-redis
      - nextcloud
    entrypoint: /cron.sh
    environment:
      - TZ=${TZ:-Asia/Shanghai}

  nextcloud-icloud-bridge:
    image: ghcr.io/trobanga/icloud-bridge:latest
    container_name: nextcloud-icloud-bridge
    restart: unless-stopped
    networks:
      - homelab_network
    depends_on:
      - nextcloud
    volumes:
      - ${DATA_PATH:-./data}/nextcloud/icloud-bridge:/app/config
    environment:
      - ICLOUD_USERNAME=
      - ICLOUD_PASSWORD=
      - NEXTCLOUD_URL=http://nextcloud:80
      - NEXTCLOUD_USERNAME=${NEXTCLOUD_ADMIN_USER:-admin}
      - NEXTCLOUD_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-change_me_now}
      - TZ=${TZ:-Asia/Shanghai}
    labels:
      - "com.github.dockge.name=nextcloud-icloud-bridge"
      - "com.github.dockge.description=iCloud与Nextcloud同步桥接"

networks:
  homelab_network:
    external: true
    name: ${NETWORK_NAME:-homelab_network}
