# version: "3.8"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    networks:
      - homelab_network
    ports:
      - 80:80 # HTTP
      - 443:443 # HTTPS
      - 8082:8080 # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA_PATH:-./data}/traefik/config:/etc/traefik
      - ${DATA_PATH:-./data}/traefik/letsencrypt:/letsencrypt
    env_file:
      - ../../.env
    environment:
      - TZ=${TZ:-Asia/Shanghai}
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=${SSL_EMAIL:-admin@example.com}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.github.dockge.name=traefik"
      - "com.github.dockge.description=反向代理与负载均衡服务"
      - "com.github.dockge.icon=https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo.png"
      - "com.github.dockge.web=http://localhost:8082"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAINNAME:-home.local}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"

networks:
  homelab_network:
    external: true
    name: ${NETWORK_NAME:-homelab_network}
