version: '3.8'

services:
  duplicati:
    image: duplicati/duplicati:latest
    container_name: duplicati
    restart: unless-stopped
    networks:
      - homelab_network
    volumes:
      - ${DATA_PATH:-./data}/duplicati/config:/config
      - ${DATA_PATH:-./data}:/source
      - ${BACKUP_PATH:-/Volumes/HDD/Backup}:/backup
      - ${MEDIA_PATH:-/Volumes/HDD/Media}:/media:ro
    environment:
      - TZ=${TZ:-Asia/Shanghai}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - 8200:8200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/api/v1/serverstate"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.github.dockge.name=duplicati"
      - "com.github.dockge.description=自动备份系统"
      - "com.github.dockge.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/duplicati-icon.png"
      - "com.github.dockge.web=http://duplicati.${DOMAINNAME:-home.local}"
      - "traefik.enable=true"
      - "traefik.http.routers.duplicati.rule=Host(`duplicati.${DOMAINNAME:-home.local}`)"
      - "traefik.http.routers.duplicati.entrypoints=websecure"
      - "traefik.http.routers.duplicati.tls=true"

networks:
  homelab_network:
    external: true
    name: ${NETWORK_NAME:-homelab_network}
