version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - homelab_network
    volumes:
      - ${DATA_PATH:-./data}/jellyfin/config:/config
      - ${JELLYFIN_CACHE_DIR:-${DATA_PATH}/jellyfin/cache}:/cache
      - ${MEDIA_PATH:-./media}:/media
    environment:
      - JELLYFIN_PublishedServerUrl=jellyfin.${DOMAINNAME:-home.local}
      - TZ=${TZ:-Asia/Shanghai}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - 8096:8096
      - 8920:8920 # HTTPS端口
      - 7359:7359/udp # 服务发现
      - 1900:1900/udp # DLNA
    devices:
      - /dev/dri:/dev/dri # 硬件加速
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.github.dockge.name=jellyfin"
      - "com.github.dockge.description=开源媒体服务器"
      - "com.github.dockge.icon=https://raw.githubusercontent.com/jellyfin/jellyfin/master/deployment/rpm/jellyfin.png"
      - "com.github.dockge.web=http://jellyfin.${DOMAINNAME:-home.local}"
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAINNAME:-home.local}`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls=true"

  kodi-companion:
    image: linuxserver/kodi-headless:latest
    container_name: kodi-companion
    restart: unless-stopped
    networks:
      - homelab_network
    volumes:
      - ${DATA_PATH:-./data}/kodi/config:/config/.kodi
      - ${MEDIA_PATH:-./media}:/media:ro
    environment:
      - TZ=${TZ:-Asia/Shanghai}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - 8080:8080
      - 9090:9090
    depends_on:
      - jellyfin
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.github.dockge.name=kodi-companion"
      - "com.github.dockge.description=Kodi无头版与Jellyfin配合使用"

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    networks:
      - homelab_network
    volumes:
      - ${DATA_PATH:-./data}/jellyseerr/config:/app/config
    environment:
      - TZ=${TZ:-Asia/Shanghai}
      - LOG_LEVEL=debug
    ports:
      - 5055:5055
    depends_on:
      - jellyfin
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.github.dockge.name=jellyseerr"
      - "com.github.dockge.description=Jellyfin的媒体请求管理系统"
      - "com.github.dockge.web=http://jellyseerr.${DOMAINNAME:-home.local}"
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.${DOMAINNAME:-home.local}`)"
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr.tls=true"

networks:
  homelab_network:
    external: true
    name: ${NETWORK_NAME:-homelab_network}
